title: "MMDesign BG"
description: "Interior design and consulting company based in Bulgaria"
baseurl: "" # leave empty for root domain
url: "http://mmdesign-bg.eu"

# GitHub Pages allows only certain safe plugins
# Don't forget to include this line to avoid plugin warnings
github:
  is_project_page: false

# Optional: exclude files/folders from the site build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
